apiVersion: v1
kind: ConfigMap
metadata:
  name: test-redis-config
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.4
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100M
              memory: 100Mi
          command:
            - "redis-server"
            - "/redis-master/redis.conf"
          env:
            - name: MASTER
              value: "true"
            - name: REDIS_PASSWORD
              value: "@Finanto.123"
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
            - mountPath: /redis-master
              name: config 
      volumes: 
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: test-redis-config
            items:
              - key: redis-config
                path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    cloud.google.com/backend-config: '{"default": "http-backend-timeout"}'
spec:
  selector:
    app: redis
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
      name: http

